name: "MRRP Lab"
description: "This is the official web page for the MRRP Lab at WWU."

url: "https://mrrp.cs.wwu.edu"
baseurl: /
lsi: false
safe: true
highlighter: rouge
gist:
  noscript: false

paginate: 5
plugins: [jekyll-paginate]
paginate_path: "news/page:num"

permalink: pretty
markdown: kramdown
kramdown:
  parse_block_html: true
  math_engine: mathjax
  syntax_highlighter: rouge

exclude:
        - .sass-cache/
        - .jekyll-cache/
        - gemfiles/
        - Gemfile
        - Gemfile.lock
        - node_modules/
        - vendor/bundle/
        - vendor/cache/
        - vendor/gems/
        - vendor/ruby/

include:
        - _site/

collections:
        affiliates:
                output: false
        members:
                output: true
        publications:
                output: true
        reviews:
                output: false
        alumni:
                output: true
        sep:
                output: true
        visitors:
                output: false
        undergrads:
                output: true
        pets:
                output: true
        tags:
                output: true
